#vscode-extension-for-zowe-1.8.0.vsix Workflow name for GitHub Actions
name: Theia Zowe Explorer CI

on: [push, pull_request]

jobs:

  theia-build:

    runs-on: ubuntu-latest

    env:
      DIST: packages/zowe-explorer/dist

    steps:
      - uses: actions/checkout@v2

      - run: yarn install --frozen-lockfile

      - name: Build vsix
        run: yarn workspace vscode-extension-for-zowe run package

      - name: Create extension install directory
        run: mkdir -p temp/plugins && chmod -R 777 temp

      - name: Copy vsix
        run: cp "${PWD}/${{ env.DIST }}/vscode-extension-for-zowe.vsix" temp/plugins

      # Verify vsix
      - run: ls -la "${PWD}/${{ env.DIST }}"
      - run: ls -la "${PWD}/temp/plugins"

      - name: Start Theia
        run: docker run --name theia --init -d -p 3000:3000 -v "${PWD}/temp:/home/theia/.theia" theiaide/theia
      # NOTE(Kelosky): alternatively, we could run docker via something like this; however, we cannot hot reload 
      #                hosted VS Code extensions after theia is started (at least at the time this was written).
      # services:
      #   theia:
      #     image: theiaide/theia:next
      #     ports:
      #       - 3000:3000
      #     volumes:
      #       - temp:/home/theia/.theia
      #     # --health-cmd "curl --fail http://localhost:3000 || exit 1" --health-interval=5s --health-timeout=5s --health-retries 60 
      #     options: --init

      - name: Upload vsix
        uses: actions/upload-artifact@v1
        with:
          name: vscode-extension-for-zowe.vsix
          path: "${{ env.DIST }}/vscode-extension-for-zowe.vsix"

      - name: Verify plugin loaded
        run: docker exec -i theia ls -la .theia/plugins

      - name: Verify Theia accessible
        run: curl --fail http://localhost:3000 --retry-max-time 10 --trace-ascii dump.txt || exit 0

      - name: Show diagnostics
        run: cat dump.txt

      - name: Show theia logs
        run: docker logs theia

      - run: yarn workspace vscode-extension-for-zowe test:theia

